services:
  - type: web
    name: heavy-tracking-api
    env: node
    plan: free
    buildCommand: npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: heavy-tracking-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password
      - key: TWILIO_ACCOUNT_SID
        value: your-twilio-sid
      - key: TWILIO_AUTH_TOKEN
        value: your-twilio-token
      - key: TWILIO_PHONE_NUMBER
        value: +1234567890
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: API_BASE_URL
        value: https://heavy-tracking-api.onrender.com/api/v1
